# Generated by Django 4.0.1 on 2023-05-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='serial_number',
            field=models.CharField(default=123456789, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SupervisorAPIKey',
        ),
    ]
