# Generated by Django 4.0.1 on 2023-05-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_supervisor_serial_number_delete_supervisorapikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='serial_number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
