# Generated by Django 4.2 on 2023-05-22 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0004_alter_supervisor_serial_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supervisor',
            options={'verbose_name': 'supervisor', 'verbose_name_plural': 'supervisors'},
        ),
    ]
