# Generated by Django 4.2 on 2023-05-22 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_qualification_options_alter_task_options_and_more'),
        ('iot', '0005_alter_supervisor_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CR', 'Created'), ('RC', 'Received'), ('IC', 'IoT creating'), ('DL', 'Delivering'), ('CM', 'Completed'), ('RJ', 'Rejected')])),
                ('last_changed', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address_of_delivery', models.TextField()),
                ('comment', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
            options={
                'verbose_name': 'offer',
                'verbose_name_plural': 'offers',
            },
        ),
    ]
