# Generated by Django 4.2 on 2023-05-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0006_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='address_of_delivery',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='offer',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('CR', 'Created'), ('RC', 'Received'), ('IC', 'IoT creating'), ('DL', 'Delivering'), ('CM', 'Completed'), ('RJ', 'Rejected')], default='CR', max_length=2),
        ),
    ]
