# Generated by Django 4.2 on 2023-05-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_techsupportrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='techsupportrequest',
            name='status',
            field=models.CharField(choices=[('CR', 'Created'), ('VW', 'Viewed'), ('CL', 'Closed')], default='CR', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='techsupportrequest',
            name='admin_response',
            field=models.TextField(null=True),
        ),
    ]
