# Generated by Django 4.2 on 2023-05-22 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_techsupportrequest_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='techsupportrequest',
            options={'verbose_name': 'Tech support request', 'verbose_name_plural': 'Tech support requests'},
        ),
        migrations.AlterField(
            model_name='techsupportrequest',
            name='status',
            field=models.CharField(choices=[('CR', 'Created'), ('VW', 'Viewed'), ('CL', 'Closed')], default='CR', max_length=2),
        ),
    ]
