# Generated by Django 4.0.1 on 2023-05-08 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0011_rename_workerstasks_taskappointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workertaskcomment',
            name='task_appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='workers.taskappointment'),
        ),
    ]
