# Generated by Django 4.2 on 2023-05-23 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_qualification_options_alter_task_options_and_more'),
        ('workers', '0016_workertaskcomment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskappointment',
            name='task_appointed',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_appointment', to='companies.task'),
        ),
    ]
