# Generated by Django 4.2 on 2023-05-30 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_taskvoting_max_score_taskvoting_min_score'),
        ('workers', '0022_taskvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskvote',
            name='voting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='companies.taskvoting'),
        ),
    ]
