# Generated by Django 4.0.1 on 2023-05-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0003_alter_supervisor_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='serial_number',
            field=models.CharField(help_text='Mast be unique, and implemented in iot program code!', max_length=255, unique=True),
        ),
    ]
