# Generated by Django 4.2 on 2023-05-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_taskvoting'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskvoting',
            name='max_score',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='taskvoting',
            name='min_score',
            field=models.IntegerField(default=0),
        ),
    ]
