# Generated by Django 4.2 on 2023-05-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_techsupportrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(max_length=254, null=FutureWarning, unique=True, verbose_name='email address'),
        ),
    ]
