# Generated by Django 4.0.1 on 2023-04-25 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_rename_hours_task_estimate_hours'),
        ('workers', '0004_alter_workerstasks_time_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerlogs',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerlogs',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='companies.task'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workerlogs',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='workerlogs',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='workerlogs',
            name='type',
            field=models.CharField(choices=[('TA', 'Task appointed'), ('TD', 'Task done'), ('OC', 'Out of working place'), ('CL', 'Custom log')], default='CL', max_length=2),
        ),
        migrations.AlterField(
            model_name='workerstasks',
            name='difficulty_for_worker',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='workerstasks',
            name='is_done',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='workerstasks',
            name='time_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
