# Generated by Django 4.2 on 2023-05-23 17:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0014_workerschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskappointment',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workerschedule',
            name='friday',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='workerschedule',
            name='monday',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='workerschedule',
            name='saturday',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='workerschedule',
            name='sunday',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='workerschedule',
            name='thursday',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='workerschedule',
            name='tuesday',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='workerschedule',
            name='wednesday',
            field=models.BooleanField(default=True),
        ),
    ]
