# Generated by Django 4.2 on 2023-05-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0017_alter_taskappointment_task_appointed'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskappointment',
            name='status',
            field=models.CharField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='workerlogs',
            name='type',
            field=models.CharField(choices=[('TA', 'Task appointed'), ('TD', 'Task done'), ('TC', 'Task status changed'), ('OC', 'Out of working place'), ('CL', 'Custom log')], default='CL', max_length=2),
        ),
    ]
